### ISSUE TITLE
No source code, can you share the source code?

### ISSUE THREAD

**Issue by NineSunTaoist** [fofapro/fapro#1]
There is only the installation package.
No source code, can you share the source code?

**Comment by ntestoc3** [comment]
Sorry, the source code is not stable yet, so it is not open source for the time being.

**Comment by LubyRuffy** [comment]
Maybe later, maybe never.

**Comment by ocbrollingpaper** [comment]
its chinese honeypot therefor you should not use it
you are literally welcoming chinese to own your infra with it
