### ISSUE TITLE
开启vnc服务后内存占用过高

### ISSUE THREAD

**Issue by zhy27** [fofapro/fapro#11]
我在阿里云上部署了一个2G内存的节点，并开启了vnc服务。今天早上大概9点开始，它接收到了大量的vnc连接请求，直到中午1点左右宕机，内存占用从460M匀速上升到了1.8G。我查看日志时，message中是有close conn的，但是内存似乎一直没有被释放？
是我的配置有什么问题吗？配置文件只使用了默认的参数：
```json
{
  "handler": "vnc",
  "port": 5900,
  "params": {
    "challenge": "0123456789abcdef",
    "password": "1234561"
  }
},
```

**Comment by ntestoc3** [comment]
感谢反馈，会在以后版本修正

**Comment by ntestoc3** [comment]
fixed in v0.44
