### ISSUE TITLE
最新版windows11运行报错

### ISSUE THREAD

**Issue by badboycxcc** [fofapro/fapro#12]
>fapro.exe run -v -l :8080
panic: Fatal error config file: While parsing config: invalid character 'ÿ' looking for beginning of value

goroutine 1 [running]:
main.(*runCommand).Execute(0xc0001d3d80, {0x2749d80, 0x2539201, 0xc0001d3d80})
        /fapro/main.go:193 +0x11b6
main.main.func1({0x15de17e1cc0, 0xc0001d3d80}, {0xc000709740, 0x1, 0x0})
        /fapro/main.go:375 +0x66
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0003d7730, {0xc00005c090, 0x7, 0x7})
        pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:333 +0x87c
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:191
main.main()
        /fapro/main.go:378 +0x294

============================
配置使用默认生成。

**Comment by ntestoc3** [comment]
与 #6 重复

**Comment by badboycxcc** [comment]
问题找到了，在powershell下生成配置文件有错误。cmd下生成就没问题了。
