### ISSUE TITLE
[Feature Request] generate configuration for single service

### ISSUE THREAD

**Issue by zema1** [fofapro/fapro#13]
如果能有
```
./fapro genConfig -t ssh
```
之类的只生成一个配置的方法会好用一些

**Comment by ntestoc3** [comment]
谢谢建议。 建议试用[FOFA clone](https://github.com/fofapro/fapro/blob/master/README-CN.md#%E4%B8%80%E9%94%AE%E5%85%8B%E9%9A%86ip%E6%9C%8D%E5%8A%A1%E9%85%8D%E7%BD%AE)功能

**Comment by ntestoc3** [comment]
added in v0.47
