### ISSUE TITLE
windows 11 无法在web页面关闭下列服务

### ISSUE THREAD

**Issue by badboycxcc** [fofapro/fapro#14]
windows 11 无法在web页面关闭下列服务

127.0.0.1:53 | dns | UDPListen |  
127.0.0.1:123 | ntp | UDPListen |  
127.0.0.1:161 | snmp | UDPListen |  
127.0.0.1:1234 | udp_echo | UDPListen |  
127.0.0.1:5060 | sip | UDPListen |  

终端程序报错刷屏
time="2021-11-05T14:13:08+08:00" level=error msg="[udp_echo](localhost) read data error:read udp 127.0.0.1:1234: use of closed network connection\n"
time="2021-11-05T14:13:08+08:00" level=error msg="[udp_echo](localhost) read data error:read udp 127.0.0.1:1234: use of closed network connection\n"
time="2021-11-05T14:13:08+08:00" level=error msg="[ntp](localhost) read data error:read udp 127.0.0.1:123: use of closed network connection\n"
time="2021-11-05T14:13:08+08:00" level=error msg="[snmp](localhost) read data error:read udp 127.0.0.1:161: use of closed network connection\n"
time="2021-11-05T14:13:08+08:00" level=error msg="[snmp](localhost) read data error:read udp 127.0.0.1:161: use of closed network connection\n"
time="2021-11-05T14:13:08+08:00" level=error msg="[snmp](localhost) read data error:read udp 127.0.0.1:161: use of closed network connection\n"

**Comment by badboycxcc** [comment]
都是UDP协议的服务

**Comment by ntestoc3** [comment]
Fixed in [v0.43.1](https://github.com/fofapro/fapro/releases/tag/v0.43.1)

**Comment by ntestoc3** [comment]
感谢反馈，将在下个版本中修复。

**Comment by ntestoc3** [comment]
fixed in v0.44
