### ISSUE TITLE
[win10]cannot startup fapro

### ISSUE THREAD

**Issue by mfwildfire** [fofapro/fapro#19]
$ ./fapro genConfig -p ssh
{
    "version": "0.58",
    "hostname": "",
    "network": "127.0.0.1/32",
    "network_build": "localhost",
    "geo_db": "",
    "exclusions": null,
    "storage": null,
    "use_logq": false,
    "syn_dev": "",
    "icmp_dev": "",
    "udp_dev": "",
    "cert_name": "",
    "hosts": [
        {
            "ip": "127.0.0.1",
            "handlers": [
                {
                    "handler": "ssh",
                    "port": 22,
                    "params": {
                        "accounts": [
                            "root:123456:/root:0"
                        ],
                        "prompt": "$ ",
                        "server_version": "SSH-2.0-OpenSSH_7.4"
                    }
                }
            ]
        }
    ],
    "templates": null
}

$ ./fapro run -v -l :8080
time="2022-02-24T11:40:16+08:00" level=info msg="ip exclusions: []"
use disk queue: false
time="2022-02-24T11:40:16+08:00" level=info msg="log: [Wintun] NamespaceRuntimeInit: Failed to create private namespace: 拒绝访问。 (Code 0x00000005)\n"
time="2022-02-24T11:40:16+08:00" level=info msg="log: [Wintun] WintunOpenAdapter: Failed to take WireGuard pool mutex\n"
time="2022-02-24T11:40:16+08:00" level=info msg="log: [Wintun] WintunCreateAdapter: Creating adapter\n"
time="2022-02-24T11:40:16+08:00" level=info msg="log: [Wintun] WintunCreateAdapter: Failed to create new device information element: 拒绝访问。 (Code 0x00000005)\n"
panic: tun device from name error: Error creating interface: Access is denied.

goroutine 1 [running]:
main.(*runCommand).Execute(0xc00068b680, {0x1b8bd00, 0x195c601, 0xc00068b680})
        /fapro/main.go:381 +0x14e6
main.main.func1({0x250c46e8030, 0xc00068b680}, {0xc000575d40, 0x1, 0x1b52500})
        /fapro/main.go:523 +0x66
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0000f9880, {0xc0000cc010, 0x7, 0x7})
        pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:333 +0x87c
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:191
main.main()
        /fapro/main.go:526 +0x27e

**Comment by ntestoc3** [comment]
Please run fapro with administrator privileges.
