### ISSUE TITLE
报错信息：panic: ioctl: SIOCADDRT: network is unreachable

### ISSUE THREAD

**Issue by hare001** [fofapro/fapro#3]
环境：
CentOS 7
Linux bogon 3.10.0-1127.el7.x86_64 ```#1``` SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ssh.json:
```json
{
	"version": "0.36",
	"network": "192.168.1.0/24",
	"network_build": "all",
	"storage": null,
	"hosts": [
		{
			"ip": "192.168.1.103",
			"handlers": [
				{
					"handler": "ssh",
					"port": 62222,
					"params": {
						"accounts": ["root:123456:/root:0"],
						"prompt": "$ ",
						"server_version": "SSH-2.0-OpenSSH_7.4"
					}
				}
			]
		}
	]
}
```
`./fapro run --config=ssh -v`
回显如下：
```plaintext
panic: ioctl: SIOCADDRT: network is unreachable

goroutine 1 [running]:
main.(*runCommand).Execute(0xc000966cc0, 0xc0006caf30, 0x0, 0x3, 0x1b7ea01, 0x7f9f891f8098)
        D:/code/netstackserver/main.go:194 +0xe74
main.main.func1(0x7f9f891f8098, 0xc000966cc0, 0xc0006caf30, 0x0, 0x3, 0x1, 0x0)
        D:/code/netstackserver/main.go:297 +0x7e
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000451a40, 0xc00004c0d0, 0x3, 0x3, 0xd, 0x0, 0x0, 0x1db0960, 0xc0006cad20)
        C:/Users/chenpanfeng/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:333 +0x85d
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        C:/Users/chenpanfeng/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:191
main.main()
        D:/code/netstackserver/main.go:300 +0x369
```
尝试更改 network 项为特定ip地址、带掩码ip地址等，依然报错如上
只有在该项设置为 127.0.0.1 时可以正常执行 fapro run，但是此时无法从内网中其他机器访问
请问如何配置 json 文件才能在内网其他机器中访问到伪造的服务？

**Comment by ntestoc3** [comment]
network指定的192.168.1.0/24网段是否已经存在了，虚拟的网络必须是新的网络，不能与现有网段冲突。
可以使用 ip route 命令查看下路由表。

可以使用"network_build": "localhost",    "ip": "0.0.0.0" 绑定本机所有网卡

如果是虚拟网络模式下要实现局域网内互通，要再进行桥接配置。

**Comment by LubyRuffy** [comment]
> network指定的192.168.1.0/24网段是否已经存在了，虚拟的网络必须是新的网络，不能与现有网段冲突。
> 可以使用 ip route 命令查看下路由表。
> 
> 可以使用"network_build": "localhost", "ip": "0.0.0.0" 绑定本机所有网卡
> 
> 如果是虚拟网络模式下要实现局域网内互通，要再进行桥接配置。

update to FAQ, or update application tips in the console output

**Comment by ntestoc3** [comment]
Starting from  [v0.37.2](https://github.com/fofapro/fapro/releases), if you specify a virtual network that already exists on the machine, FaPro will give a panic like : 
```shell
panic: [GGN] can't init virtual network: [10.10.10.0/24], already exist subnet: [10.10.10.23/24].
```
