### ISSUE TITLE
use_logq bug

### ISSUE THREAD

**Issue by nicetomeetnode** [fofapro/fapro#30]
"version": "0.63",
    "hostname": "",
    "network": "127.0.0.1/32",
    "network_build": "localhost",
    "geo_db": "./Country.mmdb",
    "exclusions": null,
    "storage": "mysql://root:xxxx@tcp(192.168.170.33:3306)/logs",
    "use_logq": true,
    "syn_dev": "",
    "icmp_dev": "",
    "udp_dev": "",
    "cert_name": "",
-------------------------------------------------------------------------------------------------------------------------------------
使用mysql存储日志数据，并开启 "use_logq": true时，一旦请求端口服务，向队列写数据，就会出现下列报错，并关闭所有服务。若"use_logq": false时，则无问题。
-------------------------------------------------------------------------------------------------------------------------------------
INFO[0000] ip exclusions: []
use disk queue: true
INFO[0000] [LogQueue] use disk queue:-log-queue
INFO[0000] [LogQueue] runner exit.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x961097]

goroutine 20 [running]:
github.com/sirupsen/logrus.(*Entry).Bytes(...)
	pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:91
github.com/sirupsen/logrus.(*Entry).String(0x2b552a0)
	pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:97 +0x17
git.gobies.org/goby/fapro/gobygreatnetwork.(*SQLHook).Fire(0xc0003d4db0, 0xc000193ab0)
	/fapro/gobygreatnetwork/storage.go:62 +0x91
git.gobies.org/goby/fapro/pkg/logger.(*QueueWriterHook).safeFire(0xc000786db0, 0x73a7c18b1cf46ba2)
	/fapro/pkg/logger/queueWriter.go:39 +0xef
git.gobies.org/goby/fapro/pkg/logger.(*QueueWriterHook).logWriterRunner(0xc000786db0)
	/fapro/pkg/logger/queueWriter.go:86 +0x2c5
created by git.gobies.org/goby/fapro/pkg/logger.NewQueueWriterHook
	/fapro/pkg/logger/queueWriter.go:102 +0x17d
----------------------------------------------------------------------------------------------------------------------------------
请问如何解决？

**Comment by ntestoc3** [comment]
感谢反馈，下个版本解决

**Comment by nicetomeetnode** [comment]
> 感谢反馈，下个版本解决

请问大致什么时候会发布下一个版本？

**Comment by ntestoc3** [comment]
> > 感谢反馈，下个版本解决
> 
> 请问大致什么时候会发布下一个版本？

已更新
