### ISSUE TITLE
how can i config fapro.json to run fapro in the same subnet with my host

### ISSUE THREAD

**Issue by UIT19522051** [fofapro/fapro#31]
![1](https://user-images.githubusercontent.com/74549358/201534048-8f940485-ff40-45a0-a2fd-a1fe26d31fd4.png)
Excuse me, i want to run fapro in the same subnet with my host in vmware so other machines in same network can access to fake services of fapro. Is there anyway

**Comment by LubyRuffy** [comment]
config fapro network to others such as 192.168.100.0/24, then add route to the host system, after that, vm host can visit 100.0 network

**Comment by UIT19522051** [comment]
thank you
